// Employer Work Experience Letter: DRAFT for employer signature. Filled ONLY from the
// employer's own answers (never the worker's claim, except where explicitly compared).
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { styles, PdfHeader, PdfFooter } from './PdfLayout';
import { DUTIES_309A } from '../skills/309A';
import { SKILL_SETS_309A } from '../skills/309A';
import { monthEn } from '../hours';
import type { VerificationRequest, Worker } from '../types';

function dutyRow(id: string) {
  const duty = DUTIES_309A.find((d) => d.id === id);
  if (!duty) return { en: id, code: '—', title: '—' };
  const skillSet = SKILL_SETS_309A.find((s) => duty.skillSetIds.includes(s.id));
  return { en: duty.en, code: skillSet?.code ?? '—', title: skillSet?.title ?? '—' };
}

export function WevForm({
  worker,
  request,
}: {
  worker: Worker;
  request: VerificationRequest;
}) {
  const { answers, result, audit } = request;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PdfHeader subtitle="Employer Work Experience Letter" />

        <Text style={styles.h1}>Employer Work Experience Letter: DRAFT for employer signature</Text>
        <View style={styles.boxAmber}>
          <Text style={styles.p}>
            This is NOT the official Skilled Trades Ontario form. It is generated by TradePass and filled ONLY from
            the employer&apos;s own answers, recorded during a video-confirmed interview. Skilled Trades Ontario
            makes all assessment decisions.
          </Text>
        </View>

        <Text style={styles.h2}>Applicant / Trade</Text>
        <View style={styles.row}><Text style={styles.label}>Applicant</Text><Text style={styles.value}>{worker.name}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Trade</Text><Text style={styles.value}>309A Construction &amp; Maintenance Electrician</Text></View>

        <Text style={styles.h2}>Employer</Text>
        {answers && (
          <>
            <View style={styles.row}><Text style={styles.label}>Company name</Text><Text style={styles.value}>{answers.companyName}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Location</Text><Text style={styles.value}>{answers.city}, {answers.country}</Text></View>
          </>
        )}

        <Text style={styles.h2}>Supervisor</Text>
        {answers && (
          <>
            <View style={styles.row}><Text style={styles.label}>Name</Text><Text style={styles.value}>{answers.supervisorName}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Title</Text><Text style={styles.value}>{answers.supervisorTitle}</Text></View>
          </>
        )}

        <Text style={styles.h2}>Employment</Text>
        {answers && result && (
          <>
            <View style={styles.row}><Text style={styles.label}>Role</Text><Text style={styles.value}>{answers.roleTitle}</Text></View>
            <View style={styles.row}>
              <Text style={styles.label}>Dates</Text>
              <Text style={styles.value}>{monthEn(answers.startDate)} to {monthEn(answers.endDate)}</Text>
            </View>
            <View style={styles.row}><Text style={styles.label}>Hours / week</Text><Text style={styles.value}>{answers.hoursPerWeek}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Total hours (confirmed)</Text><Text style={styles.value}>{result.verifiedHours.toLocaleString('en-CA')}</Text></View>
          </>
        )}

        <Text style={styles.h2}>Duties</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={styles.tableHeaderCell}>Duty</Text>
            <Text style={[styles.tableHeaderCell, { flex: 0.5 }]}>Skill set</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1.5 }]}>Skill set title</Text>
          </View>
          {(answers?.dutyIds ?? []).map((id, i, arr) => {
            const row = dutyRow(id);
            const isLast = i === arr.length - 1;
            return (
              <View key={id} style={isLast ? styles.tableRowLast : styles.tableRow}>
                <Text style={styles.tableCell}>{row.en}</Text>
                <Text style={[styles.tableCell, { flex: 0.5 }]}>{row.code}</Text>
                <Text style={[styles.tableCell, { flex: 1.5 }]}>{row.title}</Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.h2}>Verification method</Text>
        <View style={styles.box}>
          <Text style={styles.p}>
            Recorded video confirmation, {request.completedAt ? new Date(request.completedAt).toLocaleDateString('en-CA') : '—'}, SHA-256{' '}
            {audit.videoSha256 ?? 'n/a'}, ElevenLabs conversation {audit.conversationId ?? 'n/a'}, TradePass reference {request.id}.
          </Text>
        </View>

        {result && result.discrepancies.length > 0 && (
          <>
            <Text style={styles.h2}>Discrepancies</Text>
            <View style={styles.boxAmber}>
              {result.discrepancies.map((d, i) => (
                <Text key={i} style={styles.p}>• {d}</Text>
              ))}
            </View>
          </>
        )}

        <Text style={styles.h2}>Signature</Text>
        <View style={{ flexDirection: 'row', gap: 16 }}>
          <View style={{ flex: 1 }}>
            <View style={styles.signatureBox} />
            <Text style={styles.signatureLabel}>Employer signature</Text>
          </View>
          <View style={{ flex: 1 }}>
            <View style={styles.signatureBox} />
            <Text style={styles.signatureLabel}>Date</Text>
          </View>
          <View style={{ flex: 1 }}>
            <View style={styles.signatureBox} />
            <Text style={styles.signatureLabel}>Company stamp (if applicable)</Text>
          </View>
        </View>

        <PdfFooter />
      </Page>
    </Document>
  );
}
